[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path= 'forge-cache'
test = 'test/foundry'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config